from pyspark.sql.functions import sum, desc

def revenue_by_category(df):

    """Calculate revenue generated by each category."""

    revenue_df = (
        df.groupBy("category")
        .agg(
            sum("total_amount").alias("total_revenue")
        )
        .orderBy(desc("total_revenue"))
    )


    return revenue_df
